[package]
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
name = "rfcbot-rs"
version = "0.1.0"

[dependencies]
dotenv = "0.9.0"
env_logger = "0.4"
hex = "0.2.0"
handlebars = "0.29.0"
hyper = "0.10"
hyper-native-tls = "0.2.1"
lazy_static = "0.2.0"
log = "0.3.6"
r2d2 = "0.8.2"
r2d2-diesel = "1.0.0"
rocket = "0.3.3"
rocket_codegen = "0.3.3"
rocket_contrib = "0.3.3"
rust-crypto = "0.2.36"
serde = "1.0.59"
serde_derive = "1.0.59"
serde_json = "1.0"
toml = "0.4"
url = "1.4"
urlencoded = "0.5"
maplit = "1.0.1"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.diesel]
default-features = false
features = ["postgres", "chrono"]
version = "1.3.2"
