[fcp_behaviors]

[fcp_behaviors."matrix-org/matrix-doc"]
close = true
postpone = true

[teams]

[teams.T-Core]
name = "Spec Core team"
ping = "matrix-org/spec-core-team"
members = [
  "anoadragon453",
  "ara4n",
  "dbkr",
  "erikjohnston",
  "KitsuneRal",
  "richvdh",
  "turt2live",
  "uhoreg"
]
