[fcp_behaviors]

[fcp_behaviors."test-org-blabla/agreatrepo"]
close = true
postpone = true

[teams]

[teams.T-core]
name = "Core team"
ping = "test-org-blabla/spec-core"
members = [
  "anoadragon453",
]
