[fcp_behaviors]

[fcp_behaviors."mscbot-test-org/proposals"]
close = true
postpone = true

[teams]

[teams.proposal]
name = "Spec Core team"
ping = "mscbot-test-org/spec-core-team"
members = [
  "anoadragon453"
]
